import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,writeFile,mkdir,rm} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import {chromium} from 'playwright';
const root=resolve('_site');
const types={'.html':'text/html','.js':'application/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml'};
const server=createServer(async(req,res)=>{try{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);const path=resolve(root,'.'+(pathname.endsWith('/')?pathname+'index.html':pathname));if(!path.startsWith(root+'/')){res.writeHead(403).end();return;}const bytes=await readFile(path);res.writeHead(200,{'Content-Type':types[extname(path)]||'application/octet-stream','Cache-Control':'no-store'});res.end(bytes);}catch{res.writeHead(404).end('Not found');}});
await new Promise(done=>server.listen(0,'127.0.0.1',done));
const base='http://127.0.0.1:'+server.address().port;
const original=await readFile(root+'/examples/scenes.json');
const names='x y z nx ny nz f_dc_0 f_dc_1 f_dc_2 opacity scale_0 scale_1 scale_2 rot_0 rot_1 rot_2 rot_3'.split(' ');
const count=64;
const header=Buffer.from(['ply','format binary_little_endian 1.0','element vertex '+count,...names.map(x=>'property float '+x),'end_header',''].join('\n'));
const rows=Buffer.alloc(count*68);
for(let i=0;i<count;i++){const data=[(i%4)-1.5,(Math.floor(i/4)%4)-1.5,Math.floor(i/16)-1.5,0,0,0,0.7,0.25,-0.3,2,-1.4,-1.8,-1.5,1,0,0,0];data.forEach((x,j)=>rows.writeFloatLE(x,(i*17+j)*4));}
await writeFile(root+'/test-model.ply',Buffer.concat([header,rows]));
await mkdir('test-artifacts',{recursive:true});
const browser=await chromium.launch({headless:true,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
page.on('console',msg=>{if(msg.type()==='error')console.log('BROWSER',msg.text());});
page.on('pageerror',error=>console.log('PAGEERROR',error.message));
const settle=async(expected)=>{await page.waitForFunction(()=>['loaded','error'].includes(document.getElementById('scene-status').dataset.state),null,{timeout:90000});assert.equal(await page.locator('#scene-status').getAttribute('data-state'),expected,await page.locator('#scene-status').innerText());};
try{
  await page.goto(base+'/#explore');
  await page.waitForFunction(()=>document.getElementById('scene-select').textContent.includes('No public examples'));
  assert.equal(await page.locator('#scene-frame-slot iframe').count(),0);
  await page.locator('#local-model').setInputFiles(root+'/test-model.ply');
  await settle('loaded');
  assert.ok(await page.frameLocator('#scene-frame-slot iframe').locator('canvas').count());
  await page.locator('#reset-scene').click();
  await page.locator('#scene-browser').screenshot({path:'test-artifacts/viewer-desktop.png'});
  console.log('PASS local Gaussian PLY first frame and reset');
  await page.locator('#close-scene').click();
  assert.equal(await page.locator('#scene-frame-slot iframe').count(),0);
  console.log('PASS renderer unmount');
  await page.locator('#local-model').setInputFiles({name:'xyz-only.ply',mimeType:'application/octet-stream',buffer:Buffer.from('ply\nformat ascii 1.0\nelement vertex 0\nproperty float x\nend_header\n')});
  await settle('error');
  console.log('PASS invalid Gaussian input rejected');
  await page.locator('#close-scene').click();
  await writeFile(root+'/examples/scenes.json',JSON.stringify({version:1,scenes:[{id:'fixture',name:'Synthetic test only',url:'./test-model.ply'}]}));
  await page.reload();
  await page.waitForFunction(()=>!document.getElementById('load-example').disabled);
  assert.equal(await page.locator('#scene-frame-slot iframe').count(),0);
  await page.locator('#load-example').click();
  await settle('loaded');
  console.log('PASS manual manifest and lazy model loading');
  await page.setViewportSize({width:390,height:844});
  await page.locator('#scene-browser').scrollIntoViewIfNeeded();
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Mobile horizontal overflow');
  await page.locator('#scene-browser').screenshot({path:'test-artifacts/viewer-mobile.png'});
  console.log('PASS mobile layout');
  await page.locator('#close-scene').click();
  await page.getByText('Open a model link',{exact:false}).first().click();
  await page.locator('#model-url').fill(base+'/missing.ply');
  await page.locator('#model-url-form button').click();
  await settle('error');
  console.log('PASS missing URL error state');
}finally{
  await page.screenshot({path:'test-artifacts/final-state.png',fullPage:false}).catch(()=>{});
  await writeFile(root+'/examples/scenes.json',original);
  await rm(root+'/test-model.ply',{force:true});
  await browser.close();
  await new Promise(done=>server.close(done));
}
console.log('PASS browser smoke checks; synthetic fixture not published; software CI rendering is not a hardware benchmark.');
